### ISSUE TITLE
Option "Fast Music"

### ISSUE THREAD

**Issue by contratop** [pokeinalover/PatataTube#5]
Una opcion dentro del menu principal que se llame "Fast Music" o algo similar

que solo te pida link y te baje el MP3 de una sin mas submenus ni nada

para una version muy rapida de uso de PatataTube

**Comment by pokeinalover** [comment]
Confio en tu tu sabras uwuwu

**Comment by contratop** [comment]
Ya está implementado

Esta en fase de testing
